#!/usr/bin/env bash
set -euo pipefail

# Minimal OpenNeuro downloads to test every FSL tool in public/cwl/fsl.
# Data is stored in: tests/data/openneuro/<dataset-id>
#
# Tool -> dataset coverage (downloaded here)
# - ds002979 (sub-016: T1w + BOLD + fmap):
#   bet, fast, fsl_anat, fslreorient2std, flirt, fnirt, applywarp, invwarp,
#   convertwarp, fslmaths, fslstats, fslroi, fslmerge, fslsplit, run_first_all,
#   sienax, mcflirt, slicetimer, susan, melodic, film_gls, fslmeants,
#   randomise, cluster, dual_regression, flameo, topup, fugue.
# - ds003676 (single subject, ses-3T + ses-7T T1w):
#   siena (longitudinal two timepoints).
# - ds002185 (single subject DWI):
#   probtrackx2 (run bedpostx on the downloaded DWI to generate samples).
#
# NOTE: Some tools need derived inputs (design matrices, warps, masks). Those are
# generated by your test harness from these downloads and FSL outputs.
#
# If you plan to commit these data, consider Git LFS due to size.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DATA_DIR="${FSL_TEST_DATA_DIR:-$ROOT_DIR/tests/data/openneuro}"

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

ensure_repo_data_gitignore() {
  local data_path="$1"
  local data_root="${ROOT_DIR}/tests/data"
  if [[ "$data_path" == "$data_root"* ]]; then
    mkdir -p "$data_root"
    touch "$data_root/.gitignore"
  fi
}

require_cmd aws

ensure_repo_data_gitignore "$DATA_DIR"
mkdir -p "$DATA_DIR"

AWS_NO_SIGN=(--no-sign-request)

detect_first_subject() {
  local dsid="$1"
  aws s3 ls "${AWS_NO_SIGN[@]}" "s3://openneuro.org/${dsid}/" | awk '/PRE sub-/{print $2}' | head -n1 | tr -d '/'
}

download_ds002979() {
  local dsid="ds002979"
  local sub="sub-016"
  local dest="${DATA_DIR}/${dsid}"
  mkdir -p "$dest"

  # T1w + BOLD + fieldmap for most tools (minimal: one subject).
  aws s3 sync "${AWS_NO_SIGN[@]}" "s3://openneuro.org/${dsid}/" "$dest" \
    --exclude "*" \
    --include "${sub}/anat/*T1w*.nii*" \
    --include "${sub}/anat/*T1w*.json" \
    --include "${sub}/func/*bold*.nii*" \
    --include "${sub}/func/*bold*.json" \
    --include "${sub}/fmap/*"
}

download_ds003676() {
  local dsid="ds003676"
  local sub
  sub="$(detect_first_subject "$dsid")"
  if [[ -z "$sub" ]]; then
    echo "Could not detect subject for ${dsid}" >&2
    exit 1
  fi
  local dest="${DATA_DIR}/${dsid}"
  mkdir -p "$dest"

  # Two sessions for SIENA longitudinal testing.
  aws s3 sync "${AWS_NO_SIGN[@]}" "s3://openneuro.org/${dsid}/" "$dest" \
    --exclude "*" \
    --include "${sub}/ses-3T/anat/*T1w*.nii*" \
    --include "${sub}/ses-3T/anat/*T1w*.json" \
    --include "${sub}/ses-7T/anat/*T1w*.nii*" \
    --include "${sub}/ses-7T/anat/*T1w*.json"
}

download_ds002185() {
  local dsid="ds002185"
  local sub
  sub="$(detect_first_subject "$dsid")"
  if [[ -z "$sub" ]]; then
    echo "Could not detect subject for ${dsid}" >&2
    exit 1
  fi
  local dest="${DATA_DIR}/${dsid}"
  mkdir -p "$dest"

  # DWI for probtrackx2 (you will run bedpostx to generate samples).
  aws s3 sync "${AWS_NO_SIGN[@]}" "s3://openneuro.org/${dsid}/" "$dest" \
    --exclude "*" \
    --include "${sub}*/dwi/*_dwi.nii*" \
    --include "${sub}*/dwi/*_dwi.bvec" \
    --include "${sub}*/dwi/*_dwi.bval" \
    --include "${sub}*/dwi/*_dwi.json"
}

download_ds002979
download_ds003676
download_ds002185

echo "Downloads complete."
echo "Data location: ${DATA_DIR}"
